"""initial schema

Revision ID: 36c19dee772c
Revises: 
Create Date: 2026-05-13 16:04:03.351490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c19dee772c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('usage_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_provider'), 'api_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_api_usage_usage_date'), 'api_usage', ['usage_date'], unique=False)
    op.create_table('audios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_audio_id', sa.String(length=64), nullable=False),
    sa.Column('song_name', sa.String(length=256), nullable=True),
    sa.Column('artist_name', sa.String(length=256), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audios_instagram_audio_id'), 'audios', ['instagram_audio_id'], unique=True)
    op.create_table('creators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('followers_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_username'), 'creators', ['username'], unique=True)
    op.create_table('discovered_hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('reel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('health_reel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('health_ratio', sa.Float(), server_default='0', nullable=False),
    sa.Column('activity_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovered_hashtags_health_activity', 'discovered_hashtags', [sa.literal_column('health_ratio DESC'), sa.literal_column('activity_score DESC')], unique=False)
    op.create_index('ix_discovered_hashtags_name_unique', 'discovered_hashtags', ['name'], unique=True)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_hashtag', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reels_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_source_hashtag'), 'scrape_jobs', ['source_hashtag'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_table('topic_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('member_labels', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('reel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trend_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('velocity_ratio', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_id', sa.String(length=64), nullable=False),
    sa.Column('shortcode', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_indian', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_healthcare', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), sa.Computed('CASE WHEN COALESCE(views, 0) > 0 THEN ((COALESCE(likes, 0) + COALESCE(comments, 0))::float / NULLIF(views, 0)) ELSE 0 END', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_index('ix_reels_indian_healthcare_partial', 'reels', [sa.literal_column('posted_at DESC'), sa.literal_column('likes DESC')], unique=False, postgresql_where=sa.text('is_indian = true AND is_healthcare = true'))
    op.create_index('ix_reels_indian_healthcare_posted_likes', 'reels', ['is_indian', 'is_healthcare', sa.literal_column('posted_at DESC'), sa.literal_column('likes DESC')], unique=False)
    op.create_index(op.f('ix_reels_instagram_id'), 'reels', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_reels_is_healthcare'), 'reels', ['is_healthcare'], unique=False)
    op.create_index(op.f('ix_reels_is_indian'), 'reels', ['is_indian'], unique=False)
    op.create_index(op.f('ix_reels_posted_at'), 'reels', ['posted_at'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trend_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('avg_likes', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['topic_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_snapshots_cluster_id'), 'trend_snapshots', ['cluster_id'], unique=False)
    op.create_index('ix_trend_snapshots_cluster_snapshot', 'trend_snapshots', ['cluster_id', sa.literal_column('snapshot_at DESC')], unique=False)
    op.create_table('real_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('topic_label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['topic_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_topics_cluster_id'), 'real_topics', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_real_topics_reel_id'), 'real_topics', ['reel_id'], unique=False)
    op.create_table('reel_contents',
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reel_id')
    )
    op.create_index('ix_reel_contents_caption_fts', 'reel_contents', [sa.literal_column("to_tsvector('english', caption)")], unique=False, postgresql_using='gin')
    op.create_index('ix_reel_contents_hashtags_gin', 'reel_contents', ['hashtags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reel_contents_hashtags_gin', table_name='reel_contents', postgresql_using='gin')
    op.drop_index('ix_reel_contents_caption_fts', table_name='reel_contents', postgresql_using='gin')
    op.drop_table('reel_contents')
    op.drop_index(op.f('ix_real_topics_reel_id'), table_name='real_topics')
    op.drop_index(op.f('ix_real_topics_cluster_id'), table_name='real_topics')
    op.drop_table('real_topics')
    op.drop_index('ix_trend_snapshots_cluster_snapshot', table_name='trend_snapshots')
    op.drop_index(op.f('ix_trend_snapshots_cluster_id'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_reels_posted_at'), table_name='reels')
    op.drop_index(op.f('ix_reels_is_indian'), table_name='reels')
    op.drop_index(op.f('ix_reels_is_healthcare'), table_name='reels')
    op.drop_index(op.f('ix_reels_instagram_id'), table_name='reels')
    op.drop_index('ix_reels_indian_healthcare_posted_likes', table_name='reels')
    op.drop_index('ix_reels_indian_healthcare_partial', table_name='reels', postgresql_where=sa.text('is_indian = true AND is_healthcare = true'))
    op.drop_table('reels')
    op.drop_table('topic_clusters')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_source_hashtag'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index('ix_discovered_hashtags_name_unique', table_name='discovered_hashtags')
    op.drop_index('ix_discovered_hashtags_health_activity', table_name='discovered_hashtags')
    op.drop_table('discovered_hashtags')
    op.drop_index(op.f('ix_creators_username'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_audios_instagram_audio_id'), table_name='audios')
    op.drop_table('audios')
    op.drop_index(op.f('ix_api_usage_usage_date'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_provider'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
